version: '3.8'

services:
  app:
    build: .
    container_name: crypto-wallet-app
    depends_on:
      - db
    ports:
      - "8080:8080"
    volumes:
      - ./src:/app/src
    command: sh -c "javac -d out src/app/*.java && java -cp out app.Main"
    networks:
      - crypto-network

  db:
    image: mysql:8
    container_name: crypto-wallet-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: crypto_wallet
      MYSQL_USER: root
      MYSQL_PASSWORD:
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - crypto-network


volumes:
  db_data:

networks:
  crypto-network:
